# Site settings
title: CS7345 Final
email: Yvonhu02@gmail.com
description: > # this means to ignore newlines until "baseurl:"
 Here is a collection of Yvonhu's CS7345 course labs.
baseurl: "/FinalYovnh"
url: "https://github.com/Yvonhu/FinalYovnh"
email2: yvonh@smu.edu
theme-path: theme-assets # path to header assets etc
map-api-key: AIzaSyB3U7uwIvCyq01orxppAIC1v73y-FBGygY
sass:
  sass_dir: _sass
  style: compressed

collections:
  case:
    output: true
    permalink: /case-studies/:path/
  resource:
    output: true
    permalink: /resources/:path/

# Build settings
markdown: kramdown
